name: 'Release Binaries'

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: 'write'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            name: 'fluent-types-x86_64-unknown-linux-gnu.tar.gz'

          - os: 'ubuntu-latest'
            target: 'aarch64-unknown-linux-gnu'
            name: 'fluent-types-aarch64-unknown-linux-gnu.tar.gz'

          - os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-musl'
            name: 'fluent-types-x86_64-unknown-linux-musl.tar.gz'

          - os: 'macos-latest'
            target: 'x86_64-apple-darwin'
            name: 'fluent-types-x86_64-apple-darwin.tar.gz'

          - os: 'macos-latest'
            target: 'aarch64-apple-darwin'
            name: 'fluent-types-aarch64-apple-darwin.tar.gz'

          # - os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   name: fluent-types-x86_64-pc-windows-msvc.zip

          # - os: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   name: fluent-types-aarch64-pc-windows-msvc.zip

    runs-on: '${{matrix.os}}'

    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Install Compiler Stuff'
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: apt-get update -y && apt-get install -y gcc-aarch64-linux-gnu

      - name: 'Install Toolchain'
        run: |
          rustup toolchain install stable --profile=minimal
          rustup target add ${{matrix.target}}

      - if: contains(matrix.target, '-musl') && matrix.os == 'ubuntu-latest'
        run: 'sudo apt-get install -y musl-tools'

      - name: 'Rust Build Cache'
        uses: 'Swatinem/rust-cache@v2'
        with:
          cache-on-failure: true

      - name: 'Build Binary'
        run: 'cargo build --release --target ${{matrix.target}}'

      - name: 'Prepare (macos & linux)'
        if: matrix.os != 'windows-latest'
        run: |
          pushd target/${{matrix.target}}/release
          tar czf ../../../${{matrix.name}} fluent-types
          popd
          shasum -a 256 ${{matrix.name}} | cut -d ' ' -f1 > ${{matrix.name}}.sha256.txt

      - name: 'Create Draft Release'
        uses: 'softprops/action-gh-release@v1'
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ${{matrix.name}}
            ${{matrix.name}}.sha256.txt
