name: 'Release Binaries'

on:
  push:
    branches: ['main']

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            name: 'fluent-types-x86_64-unknown-linux-gnu.tar.gz'

          - os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-musl'
            name: 'fluent-types-x86_64-unknown-linux-musl.tar.gz'

          - os: 'ubuntu-latest'
            target: 'aarch64-unknown-linux-musl'
            name: 'fluent-types-aarch64-unknown-linux-musl.tar.gz'

          - os: 'macos-latest'
            target: 'x86_64-apple-darwin'
            name: 'fluent-types-x86_64-apple-darwin.tar.gz'

          - os: 'macos-latest'
            target: 'aarch64-apple-darwin'
            name: 'fluent-types-aarch64-apple-darwin.tar.gz'

          # - os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   name: fluent-types-x86_64-pc-windows-msvc.zip

          # - os: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   name: fluent-types-aarch64-pc-windows-msvc.zip

    runs-on: '${{matrix.os}}'

    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Install Target'
        uses: 'actions-rs/toolchain@v1'
        with:
          profile: 'minimal'
          target: '${{matrix.target}}'
          toolchain: 'stable'

      - name: 'Build Binary'
        run: 'cargo build --release --target ${{matrix.target}}'

      - name: 'Prepare (macos & linux)'
        if: 'matrix.os != "windows-latest"'
        run: |
          tar czf target/${{matrix.target}}/fluent-types ${{matrix.name}}
          shasum -a 256 ${{matrix.name}} | cut -d ' ' -f1 > ${{matrix.name}}.sha256.txt

      - name: 'Create Draft Release'
        uses: 'softprops/action-gh-release@v1'
        with:
          files: |
            ${{matrix.name}}
            ${{matrix.name}}.sha256.txt
